#!/bin/bash 
### BEGIN INIT INFO
# Provides:          nrpe
# Required-Start:    $all
# Required-Stop:     $network $remote_fs $named $portmap
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description: Start/stop Nrpe service
### END INIT INFO
# Start/stop the nrpe daemon.
#
# Contributed by Andrew Ryder 06-22-02
# Slight mods by Ethan Galstad 07-09-02

NrpeBin=/usr/local/nagios/bin/nrpe
NrpeCfg=/usr/local/nagios/etc/nrpe.cfg
#
#test -f $NrpeBin || exit 0
#
#case "$1" in
#start)	echo -n "Starting nagios remote plugin daemon: nrpe"
#        start-stop-daemon --start --quiet --exec $NrpeBin -- -c $NrpeCfg -d 
##	$NrpeBin -c $NrpeCfg -d
#        echo "." 
#	;;
#stop)	echo -n "Stopping nagios remote plugin daemon: nrpe"
#        start-stop-daemon --stop --quiet --exec $NrpeBin
#        echo "."
#        ;;
#restart) echo -n "Restarting nagios remote plugin daemon: nrpe"
#        start-stop-daemon --stop --quiet --exec $NrpeBin
#        start-stop-daemon --start --quiet --exec $NrpeBin -- -c $NrpeCfg -d
#        echo "."
#        ;;
#reload|force-reload) echo -n "Reloading configuration files for nagios remote plugin daemon: nrpe"
#	# nrpe reloads automatically
#        echo "."
#        ;;
#*)	echo "Usage: /etc/init.d/nrpe start|stop|restart|reload|force-reload"
#        exit 1 
#        ;;
#esac
#exit 0
start() {
	if [ -e  /var/run/nrpe.pid ]; then
		stop
	else
		sleep 5
		if [  `cat /proc/mounts | cut -d' ' -f2 | grep -q nagios` ]; then
			mount -t nfs 10.10.16.30:/usr/local/nagios /usr/local/nagios 
		fi
		$NrpeBin -c $NrpeCfg -d 
	fi
}
stop() {
	kill `cat /var/run/nrpe.pid`
	rm /var/run/nrpe.pid
}
restart() {
	stop
	start
}
usage(){
	echo "$0 {start|stop|restart}"
}
case "$1" in
	start)		start;;
	stop)		stop;;
	restart)	restart;;
	*)		usage;;
esac 
